spring.application.name=config-server
server.port=8888


spring.cloud.config.server.git.uri=https://github.com/NeelisHere/FunTix.config-files.git
spring.cloud.config.server.git.username=NeelisHere
spring.cloud.config.server.git.password=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
#spring.cloud.config.server.git.search-paths=global,apigateway,inventoryservice,bookingservice,orderservice
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main
#spring.cloud.config.server.git.basedir=./config-cache
